### ISSUE TITLE
Sequence numbering?

### ISSUE THREAD

**Issue by ColinLondon** [littlebusters/Regexp-Rename#3]
I am trying to replace "." in artboard with a sequential number...

Find: \.
Replace $#

It doesn't work. Am I missing something?

**Comment by littlebusters** [comment]
This plugin can't add number sequentially. You should use [RenameIt](https://rodi01.github.io/RenameIt/).

**Comment by ColinLondon** [comment]
Thank you, sir!
Colin Shanley
Director, Rocket Salad
07768 722 322
 <http://www.rocketsalad.com/>
